[book]
title = "Dar Lugar à Intuição, à Revelação e à Visão Profunda"
authors = ["Ajahn Vajiro"]
language = "pt"
multilingual = false
src = "manuscript/markdown-pt"

[build]
build-dir = "book"
create-missing = true

[output.epub]
additional-css = ["assets/stylesheets/output-epub.css"]
epub-version = 3
use-default-css = false
no-section-label = true
footnote-backrefs = true
curly-quotes = true
cover-image = "desktop-cover-pt.jpg"
additional-resources = []
